const exercisesData = {
    casa: {
        day1: [
            {id:'casa_d1_01', nombre:'Aperturas en el Suelo', nombre_en:'Dumbbell Floor Fly', series:3, reps:15, cal:5, img:'casa_d1_01_floor_fly.gif', desc:'Acostado en el piso, brazos semi flexionados. Abrí en arco hasta casi tocar el suelo con los codos y cerrá apretando el pecho.', yt:'dumbbell+floor+fly+form'},
            {id:'casa_d1_02', nombre:'Press de Barra en el Suelo', nombre_en:'Barbell Floor Press', series:4, reps:10, cal:7, img:'casa_d1_02_floor_press.gif', desc:'Acostado en el piso con barra. Bajá hasta que los codos toquen el suelo y empujá fuerte hacia arriba.', yt:'barbell+floor+press+form'},
            {id:'casa_d1_03', nombre:'Remo con Barra Inclinado', nombre_en:'Barbell Bent Over Row', series:3, reps:12, cal:6, img:'casa_d1_03_bent_row.gif', desc:'Torso inclinado 45°, espalda recta. Tirá la barra hacia el ombligo y bajá controlado.', yt:'barbell+bent+over+row+form'},
            {id:'casa_d1_04', nombre:'Remo Agarre Ancho', nombre_en:'Wide Grip Barbell Row', series:3, reps:12, cal:6, img:'casa_d1_04_wide_row.gif', desc:'Agarre más ancho. Tirá hacia la parte baja del pecho, codos abiertos.', yt:'wide+grip+barbell+row+form'},
            {id:'casa_d1_05', nombre:'Elevaciones Laterales', nombre_en:'Dumbbell Lateral Raise', series:4, reps:15, cal:4, img:'casa_d1_05_lateral_raise.gif', desc:'De pie, elevá hasta nivel hombro. 2 seg subida / 3 seg bajada.', yt:'dumbbell+lateral+raise+form'},
            {id:'casa_d1_06', nombre:'Curl Alterno con Mancuernas', nombre_en:'Alternating Dumbbell Curl', series:3, reps:'15/brazo', cal:4, img:'casa_d1_06_alt_curl.gif', desc:'Codos pegados al cuerpo. Bajada lenta y controlada.', yt:'alternating+dumbbell+curl+form'},
            {id:'casa_d1_07', nombre:'Extensión de Tríceps Sobre la Cabeza', nombre_en:'Overhead Triceps Extension', series:3, reps:15, cal:4, img:'casa_d1_07_triceps_ext.gif', desc:'Mancuerna detrás de la cabeza. Extendé sin abrir los codos.', yt:'overhead+triceps+extension+form'},
        ],
        day2: [
            {id:'casa_d2_01', nombre:'Sentadilla con Barra', nombre_en:'Barbell Back Squat', series:4, reps:10, cal:10, img:'casa_d2_01_back_squat.webp', desc:'Barra en espalda alta. Bajá hasta paralelo manteniendo espalda neutra.', yt:'barbell+back+squat+form'},
            {id:'casa_d2_02', nombre:'Sentadilla Goblet', nombre_en:'Goblet Squat', series:4, reps:12, cal:8, img:'casa_d2_02_goblet_squat.gif', desc:'Sostené mancuerna al pecho. Bajá profundo manteniendo el torso firme.', yt:'goblet+squat+form'},
            {id:'casa_d2_03', nombre:'Peso Muerto Rumano', nombre_en:'Romanian Deadlift', series:4, reps:10, cal:9, img:'casa_d2_03_romanian_dl.gif', desc:'Cadera hacia atrás, barra pegada a piernas. Sentí el estiramiento en femorales.', yt:'romanian+deadlift+form'},
            {id:'casa_d2_04', nombre:'Elevación de Gemelos de Pie', nombre_en:'Standing Calf Raise', series:3, reps:20, cal:3, img:'casa_d2_04_calf_raise.gif', desc:'De puntas de pie. Subí lento y pausá arriba.', yt:'standing+calf+raise+form'},
        ],
        day3: [
            {id:'casa_d3_01', nombre:'Press de Barra en el Suelo', nombre_en:'Barbell Floor Press', series:4, reps:10, cal:7, img:'casa_d3_01_floor_press.gif', desc:'Acostado en el piso con barra. Bajá hasta que los codos toquen el suelo y empujá fuerte hacia arriba.', yt:'barbell+floor+press+form'},
            {id:'casa_d3_02', nombre:'Press de Hombros con Mancuernas', nombre_en:'Dumbbell Shoulder Press', series:4, reps:12, cal:6, img:'casa_d3_02_shoulder_press.gif', desc:'Sentado o de pie, empujá las mancuernas sobre la cabeza sin bloquear codos.', yt:'dumbbell+shoulder+press+form'},
            {id:'casa_d3_03', nombre:'Aperturas con Mancuernas', nombre_en:'Dumbbell Fly', series:3, reps:15, cal:5, img:'casa_d3_03_db_fly.gif', desc:'Brazos semi flexionados, abrí en arco controlado y cerrá contrayendo el pecho.', yt:'dumbbell+fly+form'},
            {id:'casa_d3_04', nombre:'Elevaciones Laterales', nombre_en:'Dumbbell Lateral Raise', series:4, reps:15, cal:4, img:'casa_d3_04_lateral_raise.gif', desc:'De pie, elevá hasta nivel hombro. 2 seg subida / 3 seg bajada.', yt:'dumbbell+lateral+raise+form'},
            {id:'casa_d3_05', nombre:'Extensión de Tríceps Sobre la Cabeza', nombre_en:'Overhead Triceps Extension', series:3, reps:15, cal:4, img:'casa_d3_05_triceps_ext.gif', desc:'Mancuerna detrás de la cabeza. Extendé sin abrir los codos.', yt:'overhead+triceps+extension+form'},
        ],
        day4: [
            {id:'casa_d4_01', nombre:'Remo Agarre Ancho', nombre_en:'Wide Grip Barbell Row', series:3, reps:12, cal:6, img:'casa_d4_01_wide_row.gif', desc:'Agarre ancho, tirá hacia la parte baja del pecho con codos abiertos.', yt:'wide+grip+barbell+row+form'},
            {id:'casa_d4_02', nombre:'Remo Agarre Supino', nombre_en:'Underhand Barbell Row', series:3, reps:12, cal:6, img:'casa_d4_02_underhand_row.gif', desc:'Agarre supino (palmas hacia arriba). Tirá hacia el ombligo activando bíceps y dorsal.', yt:'underhand+barbell+row+form'},
            {id:'casa_d4_03', nombre:'Vuelos Posteriores', nombre_en:'Reverse Dumbbell Fly', series:3, reps:15, cal:4, img:'casa_d4_03_reverse_fly.gif', desc:'Inclinado hacia adelante, abrí los brazos activando la parte posterior del hombro.', yt:'reverse+dumbbell+fly+form'},
            {id:'casa_d4_04', nombre:'Curl de Bíceps con Barra', nombre_en:'Barbell Curl', series:4, reps:12, cal:5, img:'casa_d4_04_barbell_curl.webp', desc:'Codos pegados al cuerpo, bajada lenta y controlada.', yt:'barbell+curl+form'},
            {id:'casa_d4_05', nombre:'Curl de Concentración', nombre_en:'Concentration Curl', series:3, reps:12, cal:4, img:'casa_d4_05_concentration_curl.gif', desc:'Sentado, codo apoyado en la rodilla. Contraé fuerte arriba.', yt:'concentration+curl+form'},
        ],
    },
    gym: {
        day1: [
            {id:'gym_d1_01', nombre:'Aperturas en Máquina', nombre_en:'Machine Chest Fly', series:3, reps:15, peso:'7 lingotes', cal:5, img:'gym_d1_01_chest_fly.gif', desc:'Espalda pegada al respaldo. Cerrá los brazos contrayendo el pecho. Volvé lento sin abrir de golpe.', yt:'https://www.youtube.com/results?search_query=machine+chest+fly+form'},
            {id:'gym_d1_02', nombre:'Press de Pecho en Máquina 90°', nombre_en:'Machine Chest Press 90°', series:4, reps:10, peso:'15 kg/lado', cal:7, img:'gym_d1_02_chest_press.gif', desc:'Empujá al frente sin bloquear codos. Controlá la bajada manteniendo el pecho abierto.', yt:'https://www.youtube.com/results?search_query=machine+chest+press+form'},
            {id:'gym_d1_03', nombre:'Remo en Polea Baja Sentado', nombre_en:'Seated Cable Row', series:3, reps:12, peso:'5 lingotes', cal:6, img:'gym_d1_03_cable_row.gif', desc:'Espalda recta. Tirá hacia el ombligo juntando escápulas. No balancear el torso.', yt:'https://www.youtube.com/results?search_query=seated+cable+row+form'},
            {id:'gym_d1_04', nombre:'Jalón al Pecho', nombre_en:'Lat Pulldown', series:3, reps:12, peso:'6 lingotes', cal:6, img:'gym_d1_04_lat_pulldown.gif', desc:'Bajá la barra al pecho llevando codos hacia abajo y atrás. Subí lento.', yt:'https://www.youtube.com/results?search_query=lat+pulldown+form'},
            {id:'gym_d1_05', nombre:'Vuelos Laterales', nombre_en:'Dumbbell Lateral Raise', series:4, reps:15, peso:'4 kg', cal:4, img:'gym_d1_05_lateral_raise.gif', desc:'Subí hasta altura de hombros sin impulso. Bajá controlado.', yt:'https://www.youtube.com/results?search_query=dumbbell+lateral+raise+form'},
            {id:'gym_d1_06', nombre:'Extensiones de Tríceps en Polea', nombre_en:'Triceps Pushdown', series:3, reps:15, peso:'4 lingotes', cal:4, img:'gym_d1_06_triceps_pushdown.webp', desc:'Extender brazos sin mover hombros. Contraer fuerte abajo.', yt:'https://www.youtube.com/results?search_query=triceps+pushdown+form'},
            {id:'gym_d1_07', nombre:'Curl de Bíceps Alterno', nombre_en:'Alternating Dumbbell Curl', series:3, reps:'15/brazo', peso:'7.5 kg', cal:4, img:'gym_d1_07_alt_curl.gif', desc:'Subí girando muñeca. Bajá lento sin balancear.', yt:'https://www.youtube.com/results?search_query=alternating+dumbbell+curl+form'},
        ],
        day2: [
            {id:'gym_d2_01', nombre:'Sentadilla en Máquina', nombre_en:'Machine Squat', series:4, reps:10, peso:'15 kg/lado', cal:10, img:'gym_d2_01_machine_squat.webp', desc:'Bajá controlado hasta paralelo. Empujá fuerte subiendo.', yt:'https://www.youtube.com/results?search_query=machine+squat+form'},
            {id:'gym_d2_02', nombre:'Prensa de Piernas 45°', nombre_en:'45° Leg Press', series:4, reps:12, peso:'40 kg/lado', cal:10, img:'gym_d2_02_leg_press.gif', desc:'Pies ancho de hombros. Bajá controlado sin despegar la espalda.', yt:'https://www.youtube.com/results?search_query=leg+press+form'},
            {id:'gym_d2_03', nombre:'Extensiones de Cuádriceps', nombre_en:'Leg Extension', series:3, reps:15, peso:'7 lingotes', cal:6, img:'gym_d2_03_leg_extension.gif', desc:'Extender piernas completamente. Contraer cuádriceps arriba.', yt:'https://www.youtube.com/results?search_query=leg+extension+form'},
            {id:'gym_d2_04', nombre:'Flexiones Acostado (Curl Femoral)', nombre_en:'Lying Leg Curl', series:4, reps:10, peso:'6 lingotes', cal:6, img:'gym_d2_04_leg_curl.gif', desc:'Flexionar llevando talones hacia glúteos. No arquear espalda.', yt:'https://www.youtube.com/results?search_query=lying+leg+curl+form'},
            {id:'gym_d2_05', nombre:'Gemelos Sentado', nombre_en:'Seated Calf Raise', series:3, reps:15, peso:'20 kg', cal:3, img:'gym_d2_05_calf_raise.gif', desc:'Subí lento en puntas. Pausá arriba y bajá controlado.', yt:'https://www.youtube.com/results?search_query=seated+calf+raise+form'},
        ],
        day3: [
            {id:'gym_d3_01', nombre:'Press Inclinado con Mancuernas', nombre_en:'Incline Dumbbell Press', series:4, reps:12, peso:'10 kg/lado', cal:7, img:'gym_d3_01_incline_press.gif', desc:'Banco inclinado 30-45°. Empujá sin bloquear codos y bajá controlado.', yt:'https://www.youtube.com/results?search_query=incline+dumbbell+press+form'},
            {id:'gym_d3_02', nombre:'Press de Pecho en Máquina 90°', nombre_en:'Machine Chest Press 90°', series:4, reps:12, peso:'15 kg/lado', cal:7, img:'gym_d3_02_chest_press.gif', desc:'Empujá al frente sin bloquear codos. Controlá la bajada manteniendo el pecho abierto.', yt:'https://www.youtube.com/results?search_query=machine+chest+press+form'},
            {id:'gym_d3_03', nombre:'Aperturas en Máquina', nombre_en:'Machine Chest Fly', series:3, reps:15, peso:'7 lingotes', cal:5, img:'gym_d3_03_chest_fly.gif', desc:'Espalda pegada al respaldo. Cerrá los brazos contrayendo el pecho.', yt:'https://www.youtube.com/results?search_query=machine+chest+fly+form'},
            {id:'gym_d3_04', nombre:'Press Militar', nombre_en:'Military Press', series:4, reps:10, peso:'7.5 kg/lado', cal:6, img:'gym_d3_04_military_press.gif', desc:'Empujá sobre la cabeza. Bajá hasta la altura de los hombros con control.', yt:'https://www.youtube.com/results?search_query=military+press+form'},
            {id:'gym_d3_05', nombre:'Vuelos Laterales', nombre_en:'Dumbbell Lateral Raise', series:3, reps:12, peso:'4 kg', cal:4, img:'gym_d3_05_lateral_raise.gif', desc:'Subí hasta altura de hombros sin impulso. Bajá controlado.', yt:'https://www.youtube.com/results?search_query=lateral+raise+form'},
            {id:'gym_d3_06', nombre:'Extensiones de Tríceps en Polea', nombre_en:'Triceps Pushdown', series:4, reps:10, peso:'4 lingotes', cal:4, img:'gym_d3_06_triceps_ext.webp', desc:'Extender brazos sin mover hombros. Contraer fuerte abajo.', yt:'https://www.youtube.com/results?search_query=triceps+pushdown+form'},
        ],
        day4: [
            {id:'gym_d4_01', nombre:'Jalón al Pecho', nombre_en:'Lat Pulldown', series:4, reps:12, peso:'5 lingotes', cal:6, img:'gym_d4_01_lat_pulldown.gif', desc:'Bajá la barra al pecho llevando codos hacia abajo y atrás. Subí lento.', yt:'https://www.youtube.com/results?search_query=lat+pulldown+form'},
            {id:'gym_d4_02', nombre:'Remo en Polea Baja Sentado', nombre_en:'Seated Cable Row', series:4, reps:10, peso:'5 lingotes', cal:6, img:'gym_d4_02_cable_row.gif', desc:'Espalda recta. Tirá hacia el ombligo juntando escápulas. No balancear el torso.', yt:'https://www.youtube.com/results?search_query=seated+cable+row+form'},
            {id:'gym_d4_03', nombre:'Remo Dorian en Máquina', nombre_en:'Machine Dorian Row', series:4, reps:10, peso:'20 kg/lado', cal:7, img:'gym_d4_03_dorian_row.jpg', desc:'Inclinado hacia adelante, tirá con agarre neutro hacia la cadera. Juntá escápulas.', yt:'https://www.youtube.com/results?search_query=dorian+row+machine+form'},
            {id:'gym_d4_04', nombre:'Peck Post', nombre_en:'Reverse Pec Deck', series:3, reps:15, peso:'5 lingotes', cal:5, img:'gym_d4_04_peck_post.gif', desc:'Sentado al revés en la máquina. Abrí los brazos activando el posterior del hombro.', yt:'https://www.youtube.com/results?search_query=reverse+pec+deck+form'},
            {id:'gym_d4_05', nombre:'Curl de Bíceps en Polea Baja', nombre_en:'Cable Bicep Curl', series:4, reps:10, peso:'3 lingotes', cal:4, img:'gym_d4_05_cable_curl.gif', desc:'Tensión constante en el bíceps. Codo fijo, contraé fuerte arriba.', yt:'https://www.youtube.com/results?search_query=cable+bicep+curl+form'},
            {id:'gym_d4_06', nombre:'Curl en Banco Scott', nombre_en:'Scott Curl / Preacher Curl', series:3, reps:12, peso:'7.5 kg', cal:4, img:'gym_d4_06_scott_curl.webp', desc:'Codo apoyado en el banco. Subí hasta contraer el bíceps, bajá lento.', yt:'https://www.youtube.com/results?search_query=preacher+curl+form'},
        ],
    }
};
